distancia=float(input("Coloque aqui uma distancia em metros:"))
KM = (distancia/1000)
hM = (distancia*10)
dam = (distancia*100)
dm = (distancia*1000)
cm = (distancia*10000)
mm = (distancia*100000)
print("A distancia de",distancia,"m correspondea :" )
print(KM,"KM")
print(hM,"hM")
print(dam,"dam")
print(cm,"cm")
print(mm,"mm")